progress on nodemailer setup - credit to chatGPT for some setup config
sillsdev/appbuilder-usercontent-management pull request #11
Opened 2023-10-30 19:21 UTC by sharonpatta

We tried doing some node mailer setup but have been running into the following error:

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ETIMEDOUT 142.251.16.108:465
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -60,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '142.251.16.108',
  port: 465,
  command: 'CONN'
}

2023-11-08 20:31 UTC, mla04762 commented on .github/workflows/lint.env
You should probably change this to the actual email server (bluevire)

2023-11-08 20:33 UTC, mla04762 commented on .github/workflows/lint.env
You should change this file so that the values are the correct server (for bluevire)

2023-11-08 21:27 UTC, chrisvire commented on .env.example
> +SMTP_SERVER_PASSWORD="V@830%r0i]Ux"
Don't put passwords in check-in!  Now I have to change that email password.

2023-11-08 21:37 UTC, chrisvire commented on .github/workflows/lint.env
No, do not put in real values in lint.env.  The variables just need to be defined so that the lint will pass.  No real credentials in checked-in files!

2023-11-08 21:38 UTC, chrisvire commented on .github/workflows/lint.env
> +SMTP_SERVER_PASSWORD="V@830%r0i]Ux"
Replace with values like "noreply@example.com", "mail.example.com", "password".

2023-11-08 21:38 UTC, chrisvire commented on .env.example
> +SMTP_SERVER_PASSWORD="V@830%r0i]Ux"
Replace with values like "noreply@example.com", "mail.example.com", "password".

2023-11-08 21:39 UTC, chrisvire commented on .github/workflows/test.yml
> +                  npm run test:integration
These shouldn't be needed of the .env file is present.

2023-11-08 21:40 UTC, chrisvire commented on src/routes/app/[id]/+page.server.ts
> +        text: 'Click the link below to verify your email:', // plain text body
This wouldn't be a good plain text content. I assume this will be replaced later.

2023-11-08 21:41 UTC, chrisvire approved these changes
Please remove all the real credentials.

2023-11-08 21:41 UTC, chrisvire requested changes
Please remove real credentials

2023-11-08 22:58 UTC, chrisvire commented
Does it not work with the .env file?

2023-11-09 16:43 UTC, chrisvire approved these changes
👍

2023-11-09 16:43 UTC, merged